language: ruby
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem install bundler
rvm:
  - 1.9.3
  - jruby-19mode
  - 2.0.0
env:
  - RAILS_ENV=test RACK_ENV=test
addons:
   code_climate:
     repo_token: 914d2ef5cd8835295d483ff2143e58ed06bb20b25aca3e451be29f8963f76f4  