language: ruby
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem install bundler
rvm:
  - 1.9.3
  - jruby-19mode
  - 2.0.0
env:
 - RAILS_ENV=test RACK_ENV=test  CODECLIMATE_REPO_TOKEN=6914d2ef5cd8835295d483ff2143e58ed06bb20b25aca3e451be29f8963f76f4 
addons:
   code_climate:
     repo_token: 914d2ef5cd8835295d483ff2143e58ed06bb20b25aca3e451be29f8963f76f4 
after_script:
  - cat lcov.info | codeclimate 